apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
spec:
  template:
    spec:
      volumes:
        - name: gorse-master-data
          persistentVolumeClaim:
            claimName: gorse-master-pvc