apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: mongo
namePrefix: mongo-

resources:
- mongo-statefulset.yaml
- mongo-service.yaml
- mongo-secret.yaml
- mongo-pv.yaml