apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
spec:
  serviceName: svc
  template:
    spec:
      containers:
        - image: mongo
          name: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo_init_username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo_init_password
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - name: dev-mongo-pvc
              mountPath: /data/db
          resources:
            limits:
              cpu: 200m
              memory: 200m
            requests:
              cpu: 100m
              memory: 100m
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - asia-northeast1-b