apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: redis

namePrefix: redis-

resources:
- redis-statefulset.yaml
- redis-service.yaml
- redis-secret.yaml
- redis-pv.yaml