apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-caolila
namePrefix: dev-

images:
- name: mongo
  # newname: gcr.io/_GCP_PROJECT_ID_/mongo
  newTag: latest
replicas:
- name: statefulset
  count: 2

resources:
- ../../../base/mongo
#- pvc-patch-01.yaml
#- pvc-patch-02.yaml

patches:
- path: stateful-patch.yaml
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: statefulset
- path: secret-patch.yaml
  target:
    kind: Secret
    name: secret
- path: pv-patch.yaml
  target:
    kind: PersistentVolume
    name: pv
# - path: pvc-patch-01.yaml
#   target:
#     kind: PersistentVolumeClaim
#     name: pvc
# - path: pvc-patch-02.yaml
#   target:
#     kind: PersistentVolumeClaim
#     name: pvc