apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
spec:
  # template:
  #   spec:
  #     volumes:
  #       - name: mongo-data
  #         persistentVolumeClaim:
  #           claimName: mongo-pvc
  volumeClaimTemplates:
  - metadata:
      name: dev-mongo-pvc
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi