apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-caolila
namePrefix: dev-

images:
- name: front
  newname: gcr.io/planar-courage-414205/caolila/front-service
  newTag: latest
replicas:
- name: deploy
  count: 2

resources:
- ../../../base/frontend

patches:
- path: deploy-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: deploy
- path: secret-patch.yaml
  target:
    kind: Secret
    name: secret
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: ingress