apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: front
namePrefix: front-

resources:
- front-deploy.yaml
- front-service.yaml
- front-secret.yaml
- front-ingress.yaml