apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-caolila
namePrefix: dev-

images:
- name: zhenghaoz/gorse-worker
  # newname: zhenghaoz/gorse-worker
  newTag: nightly
replicas:
- name: statefulset
  count: 2

resources:
- ../../../base/gorse-worker

patches:
- path: stateful-patch.yaml
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: statefulset
- path: pv-patch.yaml
  target:
    kind: PersistentVolume
    name: pv
- path: pvc-patch.yaml
  target:
    kind: PersistentVolumeClaim
    name: pvc