apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
spec:
  template:
    spec:
      containers:
      - name: gorse-worker
        volumeMounts:         
        - name: dev-caolila-worker-pvc
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: dev-caolila-worker-pvc
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi