apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: gorse-worker

namePrefix: gorse-worker-

configMapGenerator:
- name: gorse-worker-config
  files:
  - config/config.toml

resources:
- worker-stateful.yaml
- worker-service.yaml