apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - protocol: TCP
    # prometheus http
    name: gorse-worker-http
    port: 8089
    targetPort: 8089
  selector:
    app: gorse-worker
