apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: proxy
        volumeMounts:
        - name: config-volume
          mountPath: /etc/envoy
        ports:
        - containerPort: 10000
        resources:
          limits:
            cpu: 200m
            memory: 200m
          requests:
            cpu: 100m
            memory: 100m
      volumes:
      - name: config-volume
        configMap:
          name: proxy-config
          items:
          - key: envoy.yaml
            path: envoy.yaml