apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - protocol: TCP
    # prometheus http
    name: gorse-server-http
    port: 8087
    targetPort: 8087
  selector:
    app: gorse-server
