apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  template:
    spec:
      containers:
      - name: gorse-server
        volumeMounts:         
        - name: dev-caolila-server-pvc
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: dev-caolila-server-pvc
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi