apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-caolila
namePrefix: dev-

images:
- name: zhenghaoz/gorse-server
  # newname: zhenghaoz/gorse-worker
  newTag: nightly
replicas:
- name: deploy
  count: 2

resources:
- ../../../base/gorse-server

patches:
- path: deploy-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: deploy