apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  masterkey: bWFzdGVyX2tleQo=
  # masterkey: _MEILI_MASTERKEY_
  DEV_MONGO_SVC_SERVICE_HOST: ZGV2LW1vbmdvLXN2Yy5kZXYtY2FvbGlsYS5zdmMuY2x1c3Rlci5sb2NhbA==
  DEV_MONGO_SVC_SERVICE_PORT: MjcwMTc=