apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
spec:
  template:
    spec:
      containers:
      - name: search
        env:
        - name: MEILISEARCH_MASTERKEY
          valueFrom:
            secretKeyRef:
              key: masterkey
              name: dev-search-secret
        - name: MONGO_SVC_SERVICE_HOST
          valueFrom:
            secretKeyRef:
              key: DEV_MONGO_SVC_SERVICE_HOST
              name: dev-search-secret
        - name: MONGO_SVC_SERVICE_PORT
          valueFrom:
            secretKeyRef:
              key: DEV_MONGO_SVC_SERVICE_PORT
              name: dev-search-secret
        - name: MEILI_SVC
          valueFrom:
            secretKeyRef:
              key: DEV_MEILI_SVC
              name: dev-search-secret
        - name: MONGO_USER_DB_NAME
          value: "user_info"
        - name: MONGO_USER_COLLECTION_NAME
          value: "users"
  volumeClaimTemplates:
  - metadata:
      name: dev-search-pvc
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi