apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
spec:
  template:
    spec:
      containers:
      - name: search
        env:
        - name: MEILISEARCH_MASTERKEY
          valueFrom:
            secretKeyRef:
              key: masterkey
              name: dev-search-secret
        - name: DEV_MONGO_SVC_SERVICE_HOST
          valueFrom:
            secretKeyRef:
              key: DEV_MONGO_SVC_SERVICE_HOST
              name: dev-mongo-svc.dev-caolila.svc.cluster.local
        - name: DEV_MONGO_SVC_SERVICE_PORT
          valueFrom:
            secretKeyRef:
              key: DEV_MONGO_SVC_SERVICE_PORT
              name: "27017"
  volumeClaimTemplates:
  - metadata:
      name: dev-search-pvc
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi