apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: search

namePrefix: search-

configMapGenerator:
- name: meili-config
  files:
  - config/config.toml

resources:
- search-stateful.yaml
- search-service.yaml
- search-secret.yaml
- search-pv.yaml
- search-pvc.yaml