apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - protocol: TCP
    name: app
    port: 50051
    targetPort: 50051
  - protocol: TCP
    name: metrics
    port: 9100
    targetPort: 9100
  selector:
    app: search
