apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
spec:
  selector:
    matchLabels:
      app: search
  serviceName: svc
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
      - name: search
        image: search
        ports:
        - containerPort: 50051
          name: apl
        - containerPort: 9100
          name: prometheus
        command: ["./search"]
        env:
        - name: MEILISEARCH_MASTERKEY
          valueFrom:
            secretKeyRef:
              name: search-secret
              key: masterkey
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: search-secret
              key: mongo_init_username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: search-secret
              key: mongo_init_password
        resources:
          limits:
            cpu: 200m
            memory: 200m
          requests:
            cpu: 100m
            memory: 100m
        volumeMounts:
        - name: dev-search-pvc
          mountPath: /data/index
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - asia-northeast1-c