apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  template:
    spec:
      containers:
      - name: kong
        env:
          - name: KONG_DATABASE
            valueFrom:
              secretKeyRef:
                name: api-gw-secret
                key: KONG_DATABASE
          - name: KONG_PG_HOST
            valueFrom:
              secretKeyRef:
                name: api-gw-secret
                key: KONG_PG_HOST
          - name: KONG_PG_USER
            valueFrom:
              secretKeyRef:
                name: api-gw-secret
                key: KONG_PG_USER
          - name: KONG_PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: api-gw-secret
                key: KONG_PG_PASSWORD
          - name: KONG_PROXY_LISTEN
            valueFrom:
              secretKeyRef:
                name: api-gw-secret
                key: KONG_PROXY_LISTEN
        readinessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
          failureThreshold: 30