apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  MYSQL_ROOT_PW: YmFy  # bar
  MYSQL_DATABASE: Y2FvbGlsYQ== # caolila
  MYSQL_USER: ZGV2     # dev
  MYSQL_PW: cGFzc3dvcmQ=       # password