apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
spec:
  volumeClaimTemplates:
  - metadata:
      name: dev-mysql-pvc
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi