apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  template:
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: proxy-config
          items:
          - key: envoy.yaml
            path: envoy.yaml