apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-caolila
namePrefix: dev-
images:
- name: proxy
  newName: proxy
  newTag: "v0.0.1"
replicas:
- name: deploy
  count: 2

resources:
- ../../../base/proxy

configMapGenerator:
- name: proxy-config
  files:
  - config/envoy.yaml

patches:
- path: deploy-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: deploy