apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - protocol: TCP
    name: meili
    port: 7700
    targetPort: 7700
  - protocol: TCP
    name: metrics
    port: 9100
    targetPort: 9100
  selector:
    app: meili
