name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:   
  build_search:
    runs-on: ubuntu-22.04
    if: contains(github.event.head_commit.modified, 'components/search/')
    defaults:
      run:
        working-directory: components/search
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Build
      run: go build -v .

    - name: Build Docker container
      run: |
        docker build -t search .

  build_recommend:
    runs-on: ubuntu-22.04
    if: contains(github.event.head_commit.modified, 'components/recommend/')
    defaults:
      run:
        working-directory: components/recommend
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Build
      run: go build -v .

    - name: Build Docker container
      run: |
        docker build -t recommend .

  build_frontend:
    runs-on: ubuntu-22.04
    if: contains(github.event.head_commit.modified, 'components/front-service/')
    defaults:
      run:
        working-directory: components/front-service
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm ci
    - name: Build TypeScript
      run: npm run build